name: Build

on:
  push:
    branches:  [ "main" ]

permissions:
  contents: write

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn clean install