name: Docker

on:
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Log In
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

      - name: Build image
        run: docker build -t 4rter/calculator:${{ github.sha }} .

      - name: Push image
        run: docker push 4rter/calculator:${{ github.sha }}