name: Docker

on:
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t 4rter/calculator:${{ github.sha }} .

      - name: Docker push
        run: docker push 4rter/calculator:${{ github.sha }}