name: Tests
on: [ push, pull_request ]

permissions:
  contents: write
  checks: write
  id-token: write

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build
        run: mvn clean install

      - name: Test
        run: mvn test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true